INSERT INTO FlorOrigem (Descricao) VALUES ('Afeganistão');
INSERT INTO FlorOrigem (Descricao) VALUES ('África do Sul');
INSERT INTO FlorOrigem (Descricao) VALUES ('Åland, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Albânia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Alemanha');
INSERT INTO FlorOrigem (Descricao) VALUES ('Andorra');
INSERT INTO FlorOrigem (Descricao) VALUES ('Angola');
INSERT INTO FlorOrigem (Descricao) VALUES ('Anguilla');
INSERT INTO FlorOrigem (Descricao) VALUES ('Antárctida');
INSERT INTO FlorOrigem (Descricao) VALUES ('Antigua e Barbuda');
INSERT INTO FlorOrigem (Descricao) VALUES ('Antilhas Holandesas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Arábia Saudita');
INSERT INTO FlorOrigem (Descricao) VALUES ('Argélia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Argentina');
INSERT INTO FlorOrigem (Descricao) VALUES ('Arménia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Aruba');
INSERT INTO FlorOrigem (Descricao) VALUES ('Austrália');
INSERT INTO FlorOrigem (Descricao) VALUES ('Áustria');
INSERT INTO FlorOrigem (Descricao) VALUES ('Azerbeijão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bahamas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bahrain');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bangladesh');
INSERT INTO FlorOrigem (Descricao) VALUES ('Barbados');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bélgica');
INSERT INTO FlorOrigem (Descricao) VALUES ('Belize');
INSERT INTO FlorOrigem (Descricao) VALUES ('Benin');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bermuda');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bielo-Rússia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bolívia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bósnia-Herzegovina');
INSERT INTO FlorOrigem (Descricao) VALUES ('Botswana');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bouvet, Ilha');
INSERT INTO FlorOrigem (Descricao) VALUES ('Brasil');
INSERT INTO FlorOrigem (Descricao) VALUES ('Brunei');
INSERT INTO FlorOrigem (Descricao) VALUES ('Bulgária');
INSERT INTO FlorOrigem (Descricao) VALUES ('Burkina Faso');
INSERT INTO FlorOrigem (Descricao) VALUES ('Burundi');
INSERT INTO FlorOrigem (Descricao) VALUES ('Butão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Cabo Verde');
INSERT INTO FlorOrigem (Descricao) VALUES ('Cambodja');
INSERT INTO FlorOrigem (Descricao) VALUES ('Camarões');
INSERT INTO FlorOrigem (Descricao) VALUES ('Canadá');
INSERT INTO FlorOrigem (Descricao) VALUES ('Cayman, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Cazaquistão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Centro-africana, República');
INSERT INTO FlorOrigem (Descricao) VALUES ('Chade');
INSERT INTO FlorOrigem (Descricao) VALUES ('Checa, República');
INSERT INTO FlorOrigem (Descricao) VALUES ('Chile');
INSERT INTO FlorOrigem (Descricao) VALUES ('China');
INSERT INTO FlorOrigem (Descricao) VALUES ('Chipre');
INSERT INTO FlorOrigem (Descricao) VALUES ('Christmas, Ilha');
INSERT INTO FlorOrigem (Descricao) VALUES ('Cocos, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Colômbia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Comores');
INSERT INTO FlorOrigem (Descricao) VALUES ('Congo, República do');
INSERT INTO FlorOrigem (Descricao) VALUES ('Congo, República Democrática do (antigo Zaire)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Cook, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Coreia do Sul');
INSERT INTO FlorOrigem (Descricao) VALUES ('Coreia, República Democrática da (Coreia do Norte)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Costa do Marfim');
INSERT INTO FlorOrigem (Descricao) VALUES ('Costa Rica');
INSERT INTO FlorOrigem (Descricao) VALUES ('Croácia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Cuba');
INSERT INTO FlorOrigem (Descricao) VALUES ('Dinamarca');
INSERT INTO FlorOrigem (Descricao) VALUES ('Djibouti');
INSERT INTO FlorOrigem (Descricao) VALUES ('Dominica');
INSERT INTO FlorOrigem (Descricao) VALUES ('Dominicana, República');
INSERT INTO FlorOrigem (Descricao) VALUES ('Egipto');
INSERT INTO FlorOrigem (Descricao) VALUES ('El Salvador');
INSERT INTO FlorOrigem (Descricao) VALUES ('Emiratos Árabes Unidos');
INSERT INTO FlorOrigem (Descricao) VALUES ('Equador');
INSERT INTO FlorOrigem (Descricao) VALUES ('Eritreia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Eslováquia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Eslovénia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Espanha');
INSERT INTO FlorOrigem (Descricao) VALUES ('Estados Unidos da América');
INSERT INTO FlorOrigem (Descricao) VALUES ('Estónia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Etiópia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Faroe, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Fiji');
INSERT INTO FlorOrigem (Descricao) VALUES ('Filipinas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Finlândia');
INSERT INTO FlorOrigem (Descricao) VALUES ('França');
INSERT INTO FlorOrigem (Descricao) VALUES ('Gabão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Gâmbia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Gana');
INSERT INTO FlorOrigem (Descricao) VALUES ('Geórgia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Geórgia do Sul e Sandwich do Sul, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Gibraltar');
INSERT INTO FlorOrigem (Descricao) VALUES ('Grécia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Grenada');
INSERT INTO FlorOrigem (Descricao) VALUES ('Gronelândia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guadeloupe');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guam');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guatemala');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guernsey');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guiana');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guiana Francesa');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guiné-Bissau');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guiné-Conacri');
INSERT INTO FlorOrigem (Descricao) VALUES ('Guiné Equatorial');
INSERT INTO FlorOrigem (Descricao) VALUES ('Haiti');
INSERT INTO FlorOrigem (Descricao) VALUES ('Heard e Ilhas McDonald, Ilha');
INSERT INTO FlorOrigem (Descricao) VALUES ('Honduras');
INSERT INTO FlorOrigem (Descricao) VALUES ('Hong Kong');
INSERT INTO FlorOrigem (Descricao) VALUES ('Hungria');
INSERT INTO FlorOrigem (Descricao) VALUES ('Iémen');
INSERT INTO FlorOrigem (Descricao) VALUES ('Índia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Indonésia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Iraque');
INSERT INTO FlorOrigem (Descricao) VALUES ('Irão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Irlanda');
INSERT INTO FlorOrigem (Descricao) VALUES ('Islândia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Israel');
INSERT INTO FlorOrigem (Descricao) VALUES ('Itália');
INSERT INTO FlorOrigem (Descricao) VALUES ('Jamaica');
INSERT INTO FlorOrigem (Descricao) VALUES ('Japão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Jersey');
INSERT INTO FlorOrigem (Descricao) VALUES ('Jordânia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Kiribati');
INSERT INTO FlorOrigem (Descricao) VALUES ('Kuwait');
INSERT INTO FlorOrigem (Descricao) VALUES ('Laos');
INSERT INTO FlorOrigem (Descricao) VALUES ('Lesoto');
INSERT INTO FlorOrigem (Descricao) VALUES ('Letónia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Líbano');
INSERT INTO FlorOrigem (Descricao) VALUES ('Libéria');
INSERT INTO FlorOrigem (Descricao) VALUES ('Líbia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Liechtenstein');
INSERT INTO FlorOrigem (Descricao) VALUES ('Lituânia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Luxemburgo');
INSERT INTO FlorOrigem (Descricao) VALUES ('Macau');
INSERT INTO FlorOrigem (Descricao) VALUES ('Macedónia, República da');
INSERT INTO FlorOrigem (Descricao) VALUES ('Madagáscar');
INSERT INTO FlorOrigem (Descricao) VALUES ('Malásia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Malawi');
INSERT INTO FlorOrigem (Descricao) VALUES ('Maldivas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Mali');
INSERT INTO FlorOrigem (Descricao) VALUES ('Malta');
INSERT INTO FlorOrigem (Descricao) VALUES ('Malvinas, Ilhas (Falkland)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Man, Ilha de');
INSERT INTO FlorOrigem (Descricao) VALUES ('Marianas Setentrionais');
INSERT INTO FlorOrigem (Descricao) VALUES ('Marrocos');
INSERT INTO FlorOrigem (Descricao) VALUES ('Marshall, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Martinica');
INSERT INTO FlorOrigem (Descricao) VALUES ('Maurícia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Mauritânia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Mayotte');
INSERT INTO FlorOrigem (Descricao) VALUES ('Menores Distantes dos Estados Unidos, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('México');
INSERT INTO FlorOrigem (Descricao) VALUES ('Myanmar (antiga Birmânia)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Micronésia, Estados Federados da');
INSERT INTO FlorOrigem (Descricao) VALUES ('Moçambique');
INSERT INTO FlorOrigem (Descricao) VALUES ('Moldávia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Mónaco');
INSERT INTO FlorOrigem (Descricao) VALUES ('Mongólia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Montenegro');
INSERT INTO FlorOrigem (Descricao) VALUES ('Montserrat');
INSERT INTO FlorOrigem (Descricao) VALUES ('Namíbia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Nauru');
INSERT INTO FlorOrigem (Descricao) VALUES ('Nepal');
INSERT INTO FlorOrigem (Descricao) VALUES ('Nicarágua');
INSERT INTO FlorOrigem (Descricao) VALUES ('Níger');
INSERT INTO FlorOrigem (Descricao) VALUES ('Nigéria');
INSERT INTO FlorOrigem (Descricao) VALUES ('Niue');
INSERT INTO FlorOrigem (Descricao) VALUES ('Norfolk, Ilha');
INSERT INTO FlorOrigem (Descricao) VALUES ('Noruega');
INSERT INTO FlorOrigem (Descricao) VALUES ('Nova Caledónia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Nova Zelândia (Aotearoa)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Oman');
INSERT INTO FlorOrigem (Descricao) VALUES ('Países Baixos (Holanda)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Palau');
INSERT INTO FlorOrigem (Descricao) VALUES ('Palestina');
INSERT INTO FlorOrigem (Descricao) VALUES ('Panamá');
INSERT INTO FlorOrigem (Descricao) VALUES ('Papua-Nova Guiné');
INSERT INTO FlorOrigem (Descricao) VALUES ('Paquistão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Paraguai');
INSERT INTO FlorOrigem (Descricao) VALUES ('Peru');
INSERT INTO FlorOrigem (Descricao) VALUES ('Pitcairn');
INSERT INTO FlorOrigem (Descricao) VALUES ('Polinésia Francesa');
INSERT INTO FlorOrigem (Descricao) VALUES ('Polónia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Porto Rico');
INSERT INTO FlorOrigem (Descricao) VALUES ('Portugal');
INSERT INTO FlorOrigem (Descricao) VALUES ('Qatar');
INSERT INTO FlorOrigem (Descricao) VALUES ('Quénia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Quirguistão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Reino Unido da Grã-Bretanha e Irlanda do Norte');
INSERT INTO FlorOrigem (Descricao) VALUES ('Reunião');
INSERT INTO FlorOrigem (Descricao) VALUES ('Roménia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Ruanda');
INSERT INTO FlorOrigem (Descricao) VALUES ('Rússia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Saara Ocidental');
INSERT INTO FlorOrigem (Descricao) VALUES ('Samoa Americana');
INSERT INTO FlorOrigem (Descricao) VALUES ('Samoa (Samoa Ocidental)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Saint Pierre et Miquelon');
INSERT INTO FlorOrigem (Descricao) VALUES ('Salomão, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('São Cristóvão e Névis (Saint Kitts e Nevis)');
INSERT INTO FlorOrigem (Descricao) VALUES ('San Marino');
INSERT INTO FlorOrigem (Descricao) VALUES ('São Tomé e Príncipe');
INSERT INTO FlorOrigem (Descricao) VALUES ('São Vicente e Granadinas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Santa Helena');
INSERT INTO FlorOrigem (Descricao) VALUES ('Santa Lúcia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Senegal');
INSERT INTO FlorOrigem (Descricao) VALUES ('Serra Leoa');
INSERT INTO FlorOrigem (Descricao) VALUES ('Sérvia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Seychelles');
INSERT INTO FlorOrigem (Descricao) VALUES ('Singapura');
INSERT INTO FlorOrigem (Descricao) VALUES ('Síria');
INSERT INTO FlorOrigem (Descricao) VALUES ('Somália');
INSERT INTO FlorOrigem (Descricao) VALUES ('Sri Lanka');
INSERT INTO FlorOrigem (Descricao) VALUES ('Suazilândia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Sudão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Suécia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Suíça');
INSERT INTO FlorOrigem (Descricao) VALUES ('Suriname');
INSERT INTO FlorOrigem (Descricao) VALUES ('Svalbard e Jan Mayen');
INSERT INTO FlorOrigem (Descricao) VALUES ('Tailândia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Taiwan');
INSERT INTO FlorOrigem (Descricao) VALUES ('Tajiquistão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Tanzânia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Terras Austrais e Antárticas Francesas (TAAF)');
INSERT INTO FlorOrigem (Descricao) VALUES ('Território Britânico do Oceano Índico');
INSERT INTO FlorOrigem (Descricao) VALUES ('Timor-Leste');
INSERT INTO FlorOrigem (Descricao) VALUES ('Togo');
INSERT INTO FlorOrigem (Descricao) VALUES ('Toquelau');
INSERT INTO FlorOrigem (Descricao) VALUES ('Tonga');
INSERT INTO FlorOrigem (Descricao) VALUES ('Trindade e Tobago');
INSERT INTO FlorOrigem (Descricao) VALUES ('Tunísia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Turks e Caicos');
INSERT INTO FlorOrigem (Descricao) VALUES ('Turquemenistão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Turquia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Tuvalu');
INSERT INTO FlorOrigem (Descricao) VALUES ('Ucrânia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Uganda');
INSERT INTO FlorOrigem (Descricao) VALUES ('Uruguai');
INSERT INTO FlorOrigem (Descricao) VALUES ('Usbequistão');
INSERT INTO FlorOrigem (Descricao) VALUES ('Vanuatu');
INSERT INTO FlorOrigem (Descricao) VALUES ('Vaticano');
INSERT INTO FlorOrigem (Descricao) VALUES ('Venezuela');
INSERT INTO FlorOrigem (Descricao) VALUES ('Vietname');
INSERT INTO FlorOrigem (Descricao) VALUES ('Virgens Americanas, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Virgens Britânicas, Ilhas');
INSERT INTO FlorOrigem (Descricao) VALUES ('Wallis e Futuna');
INSERT INTO FlorOrigem (Descricao) VALUES ('Zâmbia');
INSERT INTO FlorOrigem (Descricao) VALUES ('Zimbabwe');
